#!/bin/bash

if [ $UID -ne 0 ]; then
    echo 'This script must be run as root!' > /dev/stderr
    exit 1
fi

AUTOMOUNT_DELAY=30 # delay between calling of mount scripts

if [ -f /etc/conf.d/netctl-automount.conf ]; then
    source /etc/conf.d/netctl-automount.conf
fi

export netctl_auto_current=$(netctl-auto current)
export logtag=netctl-automount

function exec_scripts()
{
    for i in $(find /etc/netctl-automount.d/ -maxdepth 1 -type f -executable); do
        ( bash $i $1 )
    done
}

function stop_running()
{
    exec_scripts stop
    exit 0
}

trap 'stop_running' INT TERM

while true; do
    # refresh this
    export netctl_auto_current=$(netctl-auto current)

    # execute scripts
    exec_scripts start

    sleep $AUTOMOUNT_DELAY
done

# vim: set et ts=4 sw=4 sts=4:
